import { Distro } from './types';

export const DISTROS: Distro[] = [
  {
    id: 'ubuntu-linux',
    name: 'Ubuntu',
    subtitle: 'Uma poderosa distro para usuários iniciantes e intermediários.',
    logo: 'https://assets.ubuntu.com/v1/29985a98-ubuntu-logo32.png',
    categories: ['Todas as distros', 'Design', 'Servidor', 'Gnome'],
    basedOn: 'Debian',
    country: 'Ilha de Man',
    architecture: 'x64',
    isoSize: '6 GB',
    officialSite: 'https://ubuntu.com/',
    description: 'O Ubuntu é uma das distribuições Linux mais populares e amplamente utilizadas. Desenvolvido pela empresa Canonical, o Ubuntu tem como objetivo oferecer uma experiência de desktop intuitiva, amigável e acessível para usuários de todos os níveis de habilidade.',
    desktopEnvironments: 'O Ubuntu oferece diferentes ambientes de desktop, sendo o mais comum o GNOME. O GNOME é conhecido por sua interface limpa e moderna, além de proporcionar uma experiência de usuário intuitiva. Outras opções populares incluem o KDE Plasma, XFCE e MATE, cada um com suas próprias características e estilo visual.',
    mainFeatures: 'Interface amigável e intuitiva, adequada para usuários iniciantes e experientes. Atualizações regulares e suporte de longo prazo (LTS) para versões específicas, garantindo estabilidade e segurança. Grande quantidade de software disponível através do sistema de gerenciamento de pacotes APT. Integração perfeita com serviços em nuvem, como o Ubuntu One. Comunidade ativa e engajada, pronta para ajudar e compartilhar conhecimentos. Ênfase na segurança, com recursos como o AppArmor e as atualizações automáticas.',
    packageManager: 'O Ubuntu utiliza o sistema de gerenciamento de pacotes APT (Advanced Package Tool), o que facilita a instalação, atualização e remoção de software. O APT fornece uma vasta biblioteca de pacotes, permitindo que os usuários personalizem suas instalações de acordo com suas necessidades.',
    preInstalledSoftware: 'O Ubuntu vem com uma seleção de software pré-instalado, incluindo: Navegador da web (Mozilla Firefox ou Google Chrome), Suite de escritório (LibreOffice), Reprodutor multimídia (VLC Media Player), Cliente de e-mail (Mozilla Thunderbird) e Software de edição de imagens (GIMP).',
    hardwareCompatibility: 'O Ubuntu tem um bom histórico de compatibilidade com hardware diversificado. Ele suporta uma ampla variedade de dispositivos, incluindo computadores desktop, laptops, netbooks e servidores. Além disso, possui suporte para uma variedade de periféricos, como impressoras, scanners e câmeras digitais. Requisitos mínimos: Processador 2 GHz, HD/SSD 25 GB, Memória 4 GB.',
    communitySupport: 'A comunidade Ubuntu é conhecida por sua atenção e suporte aos usuários. Existem fóruns de discussão, wikis, grupos de usuários locais e canais de chat online onde os usuários podem obter ajuda, compartilhar conhecimentos e participar de discussões relacionadas ao Ubuntu.',
    comparison: 'O Ubuntu se destaca por sua interface amigável e pela grande base de usuários. Comparado a outras distribuições Linux, ele é frequentemente recomendado para iniciantes e usuários que valorizam a facilidade de uso e a estabilidade do sistema.'
  },
  {
    id: 'kali-linux',
    name: 'Kali Linux',
    subtitle: 'Kali Linux é uma distro essencial para testes de segurança e penetração.',
    logo: 'https://www.kali.org/images/kali-logo.svg',
    categories: ['Todas as distros', 'Hacking', 'Raspberry', 'Gnome', 'KDE', 'Plasma', 'LXDE', 'Mate', 'XFCE'],
    basedOn: 'Debian',
    country: 'Global',
    architecture: 'x64, arm',
    isoSize: '4 GB',
    officialSite: 'https://www.kali.org/',
    description: 'O Kali Linux é uma distribuição Linux especializada em segurança e testes de penetração. Projetado para profissionais de segurança cibernética e entusiastas, o Kali Linux oferece uma ampla gama de ferramentas e recursos para análise de segurança, exploração de vulnerabilidades e auditoria de redes.',
    desktopEnvironments: 'O Kali Linux possui suporte para vários ambientes de desktop, incluindo GNOME, KDE Plasma, Xfce e MATE. Esses ambientes de desktop oferecem interfaces intuitivas e personalizáveis, permitindo que os usuários ajustem o ambiente de trabalho de acordo com suas preferências.',
    mainFeatures: 'Ferramentas de segurança avançadas: O Kali Linux é conhecido por sua ampla gama de ferramentas de segurança cibernética. Ele oferece mais de 600 ferramentas de segurança pré-instaladas, incluindo scanners de vulnerabilidade, sniffers de rede, utilitários de quebra de senha, ferramentas de engenharia reversa e muito mais. Foco em testes de penetração: O Kali Linux é especialmente projetado para testes de penetração e avaliação de segurança. Ele fornece um conjunto de ferramentas e recursos poderosos para identificar e explorar vulnerabilidades em sistemas e redes. Atualizações regulares: O Kali Linux mantém suas ferramentas e pacotes atualizados com as últimas versões e correções de segurança. Atualizações regulares garantem que os usuários tenham acesso às últimas tecnologias e correções para manter suas atividades de segurança cibernética eficazes. Modo Live USB: O Kali Linux pode ser executado em modo Live USB, permitindo que os usuários o utilizem sem instalá-lo em seu sistema. Isso é útil para fins de teste e avaliação de segurança sem afetar o sistema operacional existente.',
    packageManager: 'O Kali Linux utiliza o sistema de gerenciamento de pacotes APT (Advanced Package Tool) do Debian. Ele permite que os usuários instalem, atualizem e removam pacotes de software de forma fácil e eficiente. O APT fornece acesso a um vasto repositório de pacotes adicionais, permitindo que os usuários ampliem as funcionalidades do Kali Linux conforme necessário.',
    preInstalledSoftware: 'O Kali Linux vem pré-instalado com uma ampla variedade de ferramentas de segurança e testes de penetração. Alguns exemplos incluem o Metasploit Framework, Wireshark, Nmap, Aircrack-ng, Burp Suite, John the Ripper e muitos outros. Essas ferramentas são selecionadas para fornecer aos usuários uma plataforma abrangente para avaliação e auditoria de segurança.',
    hardwareCompatibility: 'O Kali Linux é compatível com uma ampla gama de hardware, desde laptops e desktops até sistemas embarcados. No entanto, para aproveitar ao máximo as ferramentas de segurança avançadas e recursos de testes de penetração, é recomendado ter um hardware com suporte a recursos como placas de rede sem fio compatíveis com modo de monitoramento e injeção de pacotes. Requisitos mínimos: Processador 1 GHz, HD/SSD 10 GB, Memória 512 MB.',
    communitySupport: 'O Kali Linux possui uma comunidade ativa e engajada. Os usuários podem obter suporte por meio de fóruns de discussão, listas de e-mails, documentação oficial e outros recursos online. Além disso, a comunidade do Kali Linux contribui para o desenvolvimento contínuo da distribuição, fornecendo feedback, relatórios de bugs e contribuições de código.',
    comparison: 'O Kali Linux se destaca como uma distribuição focada em segurança e testes de penetração. Comparado a outras distribuições Linux, como o Debian ou o Ubuntu, o Kali Linux oferece uma seleção mais ampla e especializada de ferramentas de segurança pré-instaladas. Ele é altamente recomendado para profissionais de segurança cibernética e entusiastas que desejam realizar testes de penetração e análise de segurança em sistemas e redes. No entanto, para usuários que não estão envolvidos em atividades de segurança cibernética, outras distribuições podem ser mais adequadas para suas necessidades diárias.'
  },
  {
    id: 'arch-linux',
    name: 'Arch Linux',
    subtitle: 'O Arch Linux é uma distro personalizável e voltada para usuários avançados.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Arch-linux-logo.png',
    categories: ['Todas as distros', 'Raspberry', 'Servidor', 'Cinnamon', 'Gnome', 'KDE', 'Plasma', 'Mate', 'XFCE'],
    basedOn: 'Independente',
    country: 'Global',
    architecture: 'x86_64',
    isoSize: '800 MB',
    officialSite: 'https://archlinux.org/',
    description: 'O Arch Linux é uma distribuição Linux leve e flexível, focada em simplicidade, minimalismo e arquitetura “Do It Yourself” (DIY). Projetado para usuários avançados que desejam total controle sobre sua experiência Linux, o Arch Linux permite personalizar e construir um sistema sob medida, atendendo às necessidades individuais.',
    desktopEnvironments: 'O Arch Linux não possui um ambiente de desktop padrão predefinido. Em vez disso, permite que os usuários escolham e instalem manualmente o ambiente de desktop de sua preferência. Alguns dos ambientes de desktop populares suportados pelo Arch Linux incluem GNOME, KDE Plasma, Xfce, LXQt, MATE, entre outros.',
    mainFeatures: 'Modelo “Rolling Release”: O Arch Linux segue um modelo de lançamento contínuo, conhecido como “rolling release”, onde os pacotes são atualizados regularmente. Isso permite que os usuários tenham acesso às versões mais recentes de software e correções de segurança, sem a necessidade de atualizações de grandes lançamentos. Sistema de Pacotes Pacman: O Arch Linux utiliza o gerenciador de pacotes Pacman, que é rápido, eficiente e fácil de usar. O Pacman permite instalar, atualizar e remover pacotes de software de forma simples e automatizada, além de gerenciar suas dependências. AUR (Arch User Repository): O Arch Linux possui um vasto repositório de pacotes mantido pela comunidade chamado AUR. O AUR permite que os usuários acessem uma ampla variedade de pacotes adicionais, não encontrados nos repositórios oficiais, facilitando a instalação de software de terceiros. Documentação abrangente: O Arch Linux possui uma documentação extensa e bem organizada, conhecida como ArchWiki. O ArchWiki é uma fonte de informações detalhadas sobre a instalação, configuração e solução de problemas no Arch Linux, sendo uma valiosa referência para os usuários.',
    packageManager: 'O Arch Linux utiliza o gerenciador de pacotes Pacman para a instalação, atualização e remoção de software. O Pacman possui uma sintaxe simples e intuitiva, permitindo que os usuários gerenciem seus pacotes de forma eficiente. Ele também lida automaticamente com as dependências dos pacotes, garantindo a resolução correta das bibliotecas e componentes necessários.',
    preInstalledSoftware: 'O Arch Linux segue uma abordagem minimalista em relação aos pacotes pré-instalados. Durante a instalação, apenas o essencial é incluído, como o kernel do Linux, o gerenciador de inicialização (bootloader), o shell e algumas ferramentas básicas do sistema. Isso permite que os usuários personalizem sua instalação adicionando apenas os pacotes necessários para suas necessidades específicas.',
    hardwareCompatibility: 'O Arch Linux é conhecido por sua compatibilidade com uma ampla variedade de hardware. Seus pacotes são atualizados regularmente para garantir suporte aos dispositivos mais recentes. Além disso, a natureza personalizável do Arch Linux permite que os usuários ajustem e otimizem seu sistema para aproveitar ao máximo seu hardware específico. Requisitos mínimos: Processador 1 GHz, HD/SSD 10 GB, Memória 128 MB.',
    communitySupport: 'A comunidade do Arch Linux é conhecida por sua atitude de “faça você mesmo” e por oferecer um alto nível de suporte técnico. Existem fóruns de discussão, wikis e canais de bate-papo onde os usuários podem obter ajuda, compartilhar conhecimento e trocar experiências. A comunidade também contribui para o desenvolvimento de pacotes e aprimoramentos do sistema.',
    comparison: 'O Arch Linux se destaca por sua abordagem “Do It Yourself” e sua filosofia de simplicidade. Comparado a distribuições mais amigáveis para iniciantes, como o Ubuntu ou o Linux Mint, o Arch Linux requer um nível mais avançado de conhecimento e envolvimento do usuário para instalação e configuração. No entanto, essa abordagem oferece aos usuários maior controle e a capacidade de construir um sistema Linux altamente personalizado e otimizado. Para usuários que valorizam a flexibilidade e a personalização, o Arch Linux pode ser uma escolha ideal.'
  },
  {
    id: 'opensuse',
    name: 'openSUSE',
    subtitle: 'O openSUSE é uma distro segura, confiável e versátil para diversos ambientes.',
    logo: 'https://static.opensuse.org/favicon.ico',
    categories: ['Todas as distros', 'Servidor', 'Gnome', 'KDE', 'Plasma', 'LXQt', 'Mate', 'XFCE'],
    basedOn: 'Independente',
    country: 'Alemanha',
    architecture: 'x86_64',
    isoSize: '4.7 GB',
    officialSite: 'https://get.opensuse.org/',
    description: 'O openSUSE é uma distro Linux de propósito geral que oferece um equilíbrio entre estabilidade e inovação. É conhecida por sua facilidade de uso, configuração flexível e foco na comunidade. O openSUSE é adequado para uma variedade de casos de uso, desde uso doméstico e desktops corporativos até servidores e desenvolvimento de software.',
    desktopEnvironments: 'O openSUSE suporta vários ambientes de desktop, oferecendo aos usuários uma escolha flexível. Os principais ambientes de desktop disponíveis incluem o KDE Plasma, GNOME, Xfce e LXQt. Cada ambiente de desktop possui sua própria aparência, recursos e estilo de interação, permitindo que os usuários personalizem sua experiência de acordo com suas preferências.',
    mainFeatures: 'YaST (Yet another Setup Tool): O YaST é uma ferramenta de configuração exclusiva do openSUSE que fornece uma interface gráfica intuitiva para gerenciar o sistema, como configurações de hardware, rede, serviços e instalação de software. Open Build Service: O Open Build Service (OBS) é uma plataforma poderosa para a construção e distribuição de pacotes de software. Snapper: O Snapper é uma ferramenta de gerenciamento de snapshots (instantâneos) do sistema. Btrfs e XFS: O openSUSE oferece suporte a sistemas de arquivos avançados, como Btrfs e XFS.',
    packageManager: 'O openSUSE utiliza o gerenciador de pacotes Zypper, que é uma interface de linha de comando para o sistema de gerenciamento de pacotes RPM. O Zypper permite instalar, atualizar e remover pacotes de software de forma rápida e eficiente. Além disso, o openSUSE também possui uma interface gráfica chamada YaST Software Management, que fornece uma experiência amigável para gerenciar pacotes de software.',
    preInstalledSoftware: 'O openSUSE oferece uma seleção abrangente de software pré-instalados para atender às necessidades diárias dos usuários. Isso inclui navegadores da web, suítes de escritório, reprodutores de mídia, clientes de e-mail, ferramentas de desenvolvimento e muito mais.',
    hardwareCompatibility: 'O openSUSE é conhecido por sua boa compatibilidade com uma ampla gama de hardware. A distribuição é testada em uma variedade de sistemas e dispositivos para garantir um bom suporte de hardware. Requisitos mínimos: Processador 1 GHz, HD/SSD 3 GB, Memória 1 GB.',
    communitySupport: 'O openSUSE tem uma comunidade ativa e engajada de usuários e desenvolvedores. A comunidade oferece suporte por meio de fóruns de discussão, listas de e-mails, wikis e canais de bate-papo. Além disso, a documentação oficial e os recursos de suporte online fornecem informações detalhadas sobre a instalação, configuração e solução de problemas no openSUSE.',
    comparison: 'O openSUSE se destaca por sua facilidade de uso, ferramentas de configuração avançadas e flexibilidade. Comparado a outras distribuições populares, como o Ubuntu e o Fedora, o openSUSE oferece uma experiência mais personalizável e é especialmente conhecido por seu ambiente de desktop KDE Plasma bem integrado. Além disso, o openSUSE possui uma forte ênfase na comunidade e no desenvolvimento colaborativo, tornando-se uma escolha atraente para usuários que valorizam a participação ativa e a contribuição para o desenvolvimento de uma distribuição Linux.'
  },
  {
    id: 'linux-mint',
    name: 'Linux Mint',
    subtitle: 'Guia Definitivo 2026 — Simplicidade e Desktop Clássico',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Linux_Mint_logo_without_wordmark.svg_.png',
    categories: ['Todas as distros', 'Jogos', 'Educação', 'Design', 'Cinnamon', 'Gnome', 'Mate', 'XFCE'],
    basedOn: 'Ubuntu/Debian',
    country: 'Irlanda',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://linuxmint.com/',
    description: 'Linux Mint é a referência em simplicidade e conforto para usuários que buscam uma alternativa familiar ao Windows. Em 2026, continua sendo uma das distros mais recomendadas para iniciantes, focando em uma experiência "pronta para uso" com elegância e estabilidade baseada no Ubuntu LTS.',
    desktopEnvironments: 'Oferece três ambientes principais: Cinnamon (moderno e clássico), MATE (tradicional) e Xfce (leve). O Cinnamon é o destaque, proporcionando uma interface produtiva e altamente personalizável que agrada tanto novos usuários quanto veteranos.',
    mainFeatures: 'Interface familiar, ferramentas exclusivas (Mint Tools) para facilitar a configuração, e um modelo de atualizações controlado que prioriza a estabilidade do desktop. Evita o uso agressivo de pacotes Snap, preferindo o formato tradicional e Flatpaks.',
    packageManager: 'Utiliza o APT sobre a base sólida do Ubuntu LTS, garantindo anos de suporte e segurança. O Gerenciador de Aplicativos do Mint é um dos mais amigáveis do ecossistema, facilitando a descoberta e instalação de novos softwares.',
    preInstalledSoftware: 'Vem completo para o dia a dia com Firefox, LibreOffice, VLC e ferramentas de sistema intuitivas. O objetivo é que o usuário possa começar a trabalhar ou se divertir imediatamente após a instalação, sem configurações complexas.',
    hardwareCompatibility: 'Muito alta, funcionando bem em uma vasta gama de computadores. É conhecido por ser rápido e estável mesmo em máquinas que não são de última geração. Requisitos mínimos: Processador 64-bit, HD/SSD 20 GB, Memória 4 GB.',
    communitySupport: 'Possui uma das comunidades mais acolhedoras e ativas, focada em ajudar novos usuários. O suporte é excelente para quem busca resolver dúvidas cotidianas e manter o sistema funcionando sem sobressaltos.',
    comparison: 'Comparado ao Ubuntu, oferece uma experiência desktop mais clássica e refinada. Frente ao Fedora, prioriza a facilidade de uso e estabilidade sobre a inovação constante. É a porta de entrada ideal para o mundo Linux.'
  },
  {
    id: 'fedora-linux',
    name: 'Fedora',
    subtitle: 'Guia Definitivo 2026 — Inovação, Desktop e Servidores',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Fedora-logo.svg_.png',
    categories: ['Todas as distros', 'Design', 'Servidor', 'Gnome', 'KDE', 'Plasma', 'LXQt', 'XFCE'],
    basedOn: 'Independente',
    country: 'EUA',
    architecture: 'x64, arm',
    isoSize: '2 GB',
    officialSite: 'https://getfedora.org/',
    description: 'Fedora Linux é o laboratório tecnológico da Red Hat, onde as inovações do futuro são testadas hoje. Em 2026, continua sendo a distro de escolha para desenvolvedores que buscam as tecnologias mais recentes em um ambiente polido e seguro. Serve como base para o Red Hat Enterprise Linux (RHEL), equilibrando inovação com qualidade.',
    desktopEnvironments: 'O Fedora Workstation utiliza o GNOME puro como padrão, oferecendo a experiência mais fiel à visão dos desenvolvedores do ambiente. Também oferece "Spins" com KDE Plasma, XFCE e outros, todos integrando as tecnologias gráficas mais modernas como Wayland.',
    mainFeatures: 'Foco em quatro pilares: Liberdade, Inovação, Comunidade e Qualidade. Utiliza SELinux por padrão para segurança avançada, Wayland como servidor gráfico e integra-se perfeitamente com tecnologias de containers e nuvem da Red Hat.',
    packageManager: 'Utiliza o DNF (Dandified YUM), um gerenciador de pacotes moderno e eficiente. Oferece acesso rápido a versões recentes de softwares e bibliotecas, sendo ideal para quem precisa de ferramentas de desenvolvimento de ponta.',
    preInstalledSoftware: 'Vem com uma seleção moderna de aplicativos GNOME, Firefox e LibreOffice. Inclui excelentes ferramentas para gerenciamento de containers e desenvolvimento de software, refletindo sua natureza de vanguarda tecnológica.',
    hardwareCompatibility: 'É conhecido por adotar rapidamente suporte a hardware novo e melhorias de kernel, garantindo excelente performance em máquinas modernas. Requisitos mínimos: Processador 64-bit, HD/SSD 20 GB, Memória 4 GB.',
    communitySupport: 'Patrocinado pela Red Hat e desenvolvido por uma comunidade aberta e vibrante. Oferece excelente documentação e suporte focado em inovação e adoção de novos padrões da indústria de software livre.',
    comparison: 'Comparado ao Ubuntu, o Fedora é muito mais inovador e focado em tecnologias de ponta. Em relação ao Arch, oferece uma experiência mais curada e organizada com releases fixos, sendo ideal para quem quer o futuro do Linux com estabilidade.'
  },
  {
    id: 'debian-linux',
    name: 'Debian',
    subtitle: 'Guia Definitivo 2026 — Estabilidade, Servidores e Base do Ecossistema',
    logo: 'https://www.debian.org/logos/openlogo-nd-100.png',
    categories: ['Todas as distros', 'Pc antigo', 'Raspberry', 'Servidor', 'Gnome', 'KDE', 'Plasma', 'LXDE', 'XFCE'],
    basedOn: 'Independente',
    country: 'Global',
    architecture: 'Múltiplas',
    isoSize: 'Varia',
    officialSite: 'https://www.debian.org/',
    description: 'Debian Linux é sinônimo de estabilidade extrema e compromisso absoluto com o software livre. Criado em 1993, é a base técnica de centenas de outras distros, como o Ubuntu. Em 2026, continua sustentando grande parte da infraestrutura da internet e sistemas críticos mundiais através de seu modelo de desenvolvimento comunitário rigoroso.',
    desktopEnvironments: 'Suporta quase todos os ambientes gráficos disponíveis (GNOME, KDE, XFCE, etc.), permitindo uma experiência versátil tanto em desktops quanto em estações de trabalho profissionais, sempre priorizando versões de software amplamente testadas.',
    mainFeatures: 'Oferece três ramos principais: Stable (foco em servidores), Testing (equilíbrio) e Unstable/Sid (desenvolvimento). É regido pelo Contrato Social Debian, garantindo um sistema 100% livre em sua versão principal e transparência total nas decisões.',
    packageManager: 'Utiliza o robusto sistema APT / dpkg, um dos mais confiáveis do mundo Linux. Possui um dos maiores repositórios de software, com pacotes que passam por testes rigorosos de segurança e estabilidade antes de chegarem à versão Stable.',
    preInstalledSoftware: 'A seleção de software varia conforme o perfil de instalação escolhido, podendo ir de um servidor minimalista a um desktop completo com LibreOffice e Firefox. O foco é sempre em fornecer ferramentas estáveis e seguras para produção.',
    hardwareCompatibility: 'Conhecido como "O Sistema Operacional Universal", o Debian suporta uma gama enorme de arquiteturas de hardware. Requisitos mínimos: Processador 64-bit, HD/SSD 20 GB, Memória 2 GB.',
    communitySupport: 'Gerido por uma organização sem fins lucrativos com milhares de voluntários. Oferece uma das comunidades mais antigas e sólidas, com suporte focado em previsibilidade e segurança para ambientes corporativos e governamentais.',
    comparison: 'Comparado ao Ubuntu, o Debian é mais conservador e estável. Frente ao Fedora, prioriza confiabilidade sobre inovação rápida. É a rocha sobre a qual o ecossistema Linux moderno foi construído, ideal para servidores e sistemas críticos.'
  },
  {
    id: 'manjaro',
    name: 'Manjaro',
    subtitle: 'O poder do Arch Linux de forma simples e amigável.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/1634207749manjaro.png',
    categories: ['Todas as distros', 'Gnome', 'KDE', 'Plasma'],
    basedOn: 'Arch',
    country: 'Alemanha/França/Áustria',
    architecture: 'x64, arm',
    isoSize: '3 GB',
    officialSite: 'https://manjaro.org/',
    description: 'Manjaro traz a flexibilidade do Arch com instaladores fáceis e drivers pré-configurados.',
    desktopEnvironments: 'XFCE, KDE Plasma, GNOME.',
    mainFeatures: 'Pamac, acesso ao AUR, rolling release.',
    packageManager: 'Pacman/Pamac',
    preInstalledSoftware: 'Steam, Firefox, LibreOffice.',
    hardwareCompatibility: 'Excelente detecção de hardware.',
    communitySupport: 'Comunidade vibrante.',
    comparison: 'Arch para seres humanos.'
  },
  {
    id: 'deepin',
    name: 'Deepin',
    subtitle: 'Beleza e elegância com uma interface única.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Deepin_logo.svg_-scaled.png',
    categories: ['Todas as distros', 'Gnome'],
    basedOn: 'Debian',
    country: 'China',
    architecture: 'x64',
    isoSize: '3.5 GB',
    officialSite: 'https://www.deepin.org/',
    description: 'Deepin é famoso por seu ambiente de desktop (DDE) extremamente polido e bonito.',
    desktopEnvironments: 'Deepin Desktop Environment (DDE).',
    mainFeatures: 'Interface visual deslumbrante, Deepin Store.',
    packageManager: 'APT',
    preInstalledSoftware: 'Deepin Apps (Music, Movie, etc).',
    hardwareCompatibility: 'Boa.',
    communitySupport: 'Crescente internacionalmente.',
    comparison: 'O Linux mais bonito "out of the box".'
  },
  {
    id: 'xubuntu',
    name: 'Xubuntu',
    subtitle: 'Leveza e elegância com o ambiente XFCE.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/xubuntu-computer-software-gnome-android-long-term-support-gnome.jpg',
    categories: ['Todas as distros', 'XFCE', 'Pc antigo'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://xubuntu.org/',
    description: 'Xubuntu combina a base sólida do Ubuntu com o desktop XFCE, ideal para máquinas com menos recursos.',
    desktopEnvironments: 'XFCE.',
    mainFeatures: 'Estabilidade do Ubuntu, leveza do XFCE.',
    packageManager: 'APT',
    preInstalledSoftware: 'Thunar, Firefox, LibreOffice.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Comunidade Ubuntu.',
    comparison: 'Equilíbrio perfeito entre desempenho e usabilidade.'
  },
  {
    id: 'elementary-os',
    name: 'Elementary OS',
    subtitle: 'Simplicidade, foco e um design inspirado no macOS.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/elementary-os-logo.png',
    categories: ['Todas as distros', 'Design', 'Pantheon'],
    basedOn: 'Ubuntu',
    country: 'EUA',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://elementary.io/',
    description: 'Elementary OS foca em uma experiência de usuário coesa e minimalista com seu desktop Pantheon.',
    desktopEnvironments: 'Pantheon.',
    mainFeatures: 'AppCenter, design consistente, privacidade.',
    packageManager: 'APT',
    preInstalledSoftware: 'Epiphany, Mail, Music.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Focada em design e UX.',
    comparison: 'A escolha para quem busca estética e simplicidade.'
  },
  {
    id: 'zorin-os',
    name: 'Zorin OS',
    subtitle: 'A alternativa perfeita ao Windows e macOS.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/stsmall507x507-pad600x600f8f8f8.jpg',
    categories: ['Todas as distros', 'Jogos', 'Educação', 'Design', 'Multimidia', 'Gnome', 'XFCE'],
    basedOn: 'Ubuntu',
    country: 'Irlanda',
    architecture: 'x64',
    isoSize: '3 GB',
    officialSite: 'https://zorin.com/',
    description: 'Zorin OS é projetado para ser fácil, permitindo mudar a aparência para se parecer com o Windows ou Mac.',
    desktopEnvironments: 'Zorin Desktop (baseado em GNOME/XFCE).',
    mainFeatures: 'Zorin Appearance, Zorin Connect.',
    packageManager: 'APT',
    preInstalledSoftware: 'LibreOffice, Firefox, GIMP.',
    hardwareCompatibility: 'Excelente.',
    communitySupport: 'Muito acolhedora para novos usuários.',
    comparison: 'Melhor porta de entrada para quem sai do Windows.'
  },
  {
    id: 'mx-linux',
    name: 'MX Linux',
    subtitle: 'Estabilidade, ferramentas úteis e alto desempenho.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/mx-linux-i46j7tf3n19gumng8vgbsl.webp',
    categories: ['Todas as distros', 'Pc antigo', 'KDE', 'Plasma', 'XFCE'],
    basedOn: 'Debian',
    country: 'Grécia/EUA',
    architecture: 'x64, x86',
    isoSize: '2 GB',
    officialSite: 'https://mxlinux.org/',
    description: 'MX Linux é uma distro de peso médio que combina um desktop elegante com configuração simples.',
    desktopEnvironments: 'XFCE (padrão), KDE, Fluxbox.',
    mainFeatures: 'MX Tools, excelente performance.',
    packageManager: 'APT',
    preInstalledSoftware: 'Firefox, LibreOffice, MX Tools.',
    hardwareCompatibility: 'Muito alta.',
    communitySupport: 'Comunidade muito ativa e prestativa.',
    comparison: 'Frequentemente no topo do DistroWatch.'
  },
  {
    id: 'slackware',
    name: 'Slackware',
    subtitle: 'A distribuição Linux mais antiga ainda em atividade.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/SlackwareBlueLogo.svg_.png',
    categories: ['Todas as distros', 'Pc antigo', 'Servidor', 'KDE', 'Plasma', 'XFCE'],
    basedOn: 'Independente',
    country: 'EUA',
    architecture: 'x64, x86',
    isoSize: '3.5 GB',
    officialSite: 'http://www.slackware.com/',
    description: 'Slackware foca em estabilidade e simplicidade no estilo Unix.',
    desktopEnvironments: 'KDE, XFCE.',
    mainFeatures: 'Simplicidade de design, sem systemd.',
    packageManager: 'pkgtool',
    preInstalledSoftware: 'Vasto conjunto de ferramentas Unix.',
    hardwareCompatibility: 'Boa, mas requer conhecimento técnico.',
    communitySupport: 'Comunidade de veteranos.',
    comparison: 'Para quem quer o Linux "puro".'
  },
  {
    id: 'bodhi',
    name: 'Bodhi Linux',
    subtitle: 'Minimalismo e o desktop Moksha.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/bodhilogo-simple.png',
    categories: ['Todas as distros', 'Pc antigo'],
    basedOn: 'Ubuntu',
    country: 'EUA',
    architecture: 'x64, x86',
    isoSize: '800 MB',
    officialSite: 'https://www.bodhilinux.com/',
    description: 'Bodhi é uma distro minimalista que usa o ambiente Moksha (fork do Enlightenment).',
    desktopEnvironments: 'Moksha.',
    mainFeatures: 'Extrema leveza, visual único.',
    packageManager: 'APT',
    preInstalledSoftware: 'Mínimo.',
    hardwareCompatibility: 'Excelente para hardware antigo.',
    communitySupport: 'Pequena mas dedicada.',
    comparison: 'Uma das distros mais leves que existem.'
  },
  {
    id: 'big-linux',
    name: 'Big Linux',
    subtitle: 'Uma das melhores distros brasileiras, focada em facilidade.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/icon-logo-biglinux.webp',
    categories: ['Todas as distros', 'Brasileira', 'KDE', 'Plasma'],
    basedOn: 'Manjaro',
    country: 'Brasil',
    architecture: 'x64',
    isoSize: '3.2 GB',
    officialSite: 'https://www.biglinux.com.br/',
    description: 'Big Linux é um projeto brasileiro que foca em oferecer um sistema completo e fácil de usar.',
    desktopEnvironments: 'KDE Plasma.',
    mainFeatures: 'Web Apps, ferramentas de otimização, suporte a drivers.',
    packageManager: 'Pacman/Pamac',
    preInstalledSoftware: 'Completo para uso diário.',
    hardwareCompatibility: 'Excelente.',
    communitySupport: 'Forte comunidade brasileira.',
    comparison: 'Orgulho nacional no mundo Linux.'
  },
  {
    id: 'lubuntu',
    name: 'Lubuntu',
    subtitle: 'Rápido e leve, perfeito para computadores antigos.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Lubuntu_logo_only.svg_.png',
    categories: ['Todas as distros', 'Pc antigo', 'Raspberry', 'LXDE', 'LXQt'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://lubuntu.me/',
    description: 'Lubuntu usa o ambiente LXQt para fornecer um sistema funcional em hardware limitado.',
    desktopEnvironments: 'LXQt.',
    mainFeatures: 'Baixo consumo de RAM, base Ubuntu.',
    packageManager: 'APT',
    preInstalledSoftware: 'PCManFM-Qt, Firefox, LibreOffice.',
    hardwareCompatibility: 'Muito alta.',
    communitySupport: 'Comunidade Ubuntu.',
    comparison: 'A versão mais leve do Ubuntu.'
  },
  {
    id: 'linux-lite',
    name: 'Linux Lite',
    subtitle: 'Simples, rápido e gratuito.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Linux_lite_light_logo_sample_sample.png',
    categories: ['Todas as distros', 'XFCE', 'Pc antigo'],
    basedOn: 'Ubuntu',
    country: 'Nova Zelândia',
    architecture: 'x64',
    isoSize: '2 GB',
    officialSite: 'https://www.linuxliteos.com/',
    description: 'Linux Lite é projetado para facilitar a transição do Windows para o Linux.',
    desktopEnvironments: 'XFCE.',
    mainFeatures: 'Lite Tweaks, fácil de usar.',
    packageManager: 'APT',
    preInstalledSoftware: 'Firefox, LibreOffice, VLC.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Focada em iniciantes.',
    comparison: 'Ótimo para reviver PCs velhos.'
  },
  {
    id: 'pop-os',
    name: 'Pop!_OS',
    subtitle: 'Desenvolvido para criadores, desenvolvedores e gamers.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Pop_OS_Icon.svg_-scaled.png',
    categories: ['Todas as distros', 'Design', 'Gnome'],
    basedOn: 'Ubuntu',
    country: 'EUA',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://pop.system76.com/',
    description: 'Pop!_OS é a distro da System76, focada em produtividade e fluxo de trabalho.',
    desktopEnvironments: 'COSMIC (baseado em GNOME).',
    mainFeatures: 'Auto Tiling, excelente suporte a NVIDIA.',
    packageManager: 'APT/Flatpak',
    preInstalledSoftware: 'Pop!_Shop, Firefox.',
    hardwareCompatibility: 'Excelente, especialmente para laptops.',
    communitySupport: 'Muito ativa.',
    comparison: 'Favorito entre desenvolvedores e gamers.'
  },
  {
    id: 'sparkylinux',
    name: 'SparkyLinux',
    subtitle: 'Leve, rápido e personalizável.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/SparkyLinux-logo-200px.png',
    categories: ['Todas as distros', 'Pc antigo', 'KDE', 'Plasma', 'LXDE', 'LXQt', 'Mate', 'XFCE'],
    basedOn: 'Debian',
    country: 'Polônia',
    architecture: 'x64, x86, arm',
    isoSize: '2 GB',
    officialSite: 'https://sparkylinux.org/',
    description: 'SparkyLinux oferece várias edições para diferentes necessidades, desde minimalistas até completas.',
    desktopEnvironments: 'LXQt, XFCE, KDE, etc.',
    mainFeatures: 'Base Debian Testing, várias edições.',
    packageManager: 'APT',
    preInstalledSoftware: 'Varia por edição.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Comunidade europeia sólida.',
    comparison: 'Debian com um toque de facilidade.'
  },
  {
    id: 'mageia',
    name: 'Mageia',
    subtitle: 'Estável, seguro e fácil de usar.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/png-clipart-mageia-linux-mint-logo-linux-distribution-linux-blue-logo.png',
    categories: ['Todas as distros', 'Cinnamon', 'Gnome', 'KDE', 'Plasma', 'LXDE', 'LXQt', 'Mate', 'XFCE'],
    basedOn: 'Mandriva',
    country: 'França',
    architecture: 'x64, x86',
    isoSize: '4 GB',
    officialSite: 'https://www.mageia.org/',
    description: 'Mageia é um fork comunitário do Mandriva Linux.',
    desktopEnvironments: 'KDE Plasma, GNOME, XFCE.',
    mainFeatures: 'Mageia Control Center.',
    packageManager: 'URPMI/DNF',
    preInstalledSoftware: 'LibreOffice, Firefox.',
    hardwareCompatibility: 'Boa.',
    communitySupport: 'Comunidade apaixonada.',
    comparison: 'Sucessor espiritual do Mandriva.'
  },
  {
    id: 'tails',
    name: 'Tails',
    subtitle: 'Privacidade e anonimato em qualquer lugar.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/raf360x360075tfafafa_ca443f4786.u1.jpg',
    categories: ['Todas as distros', 'Hacking', 'Gnome'],
    basedOn: 'Debian',
    country: 'Global',
    architecture: 'x64',
    isoSize: '1.2 GB',
    officialSite: 'https://tails.boum.org/',
    description: 'Tails é um sistema live que força todas as conexões através da rede Tor.',
    desktopEnvironments: 'GNOME.',
    mainFeatures: 'Amnésico, focado em segurança total.',
    packageManager: 'APT',
    preInstalledSoftware: 'Tor Browser, Thunderbird, KeePassXC.',
    hardwareCompatibility: 'Focada em boot via USB.',
    communitySupport: 'Focada em ativistas e jornalistas.',
    comparison: 'O padrão ouro para privacidade.'
  },
  {
    id: 'parrot-os',
    name: 'Parrot OS',
    subtitle: 'Segurança, privacidade e desenvolvimento.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/257-2578920_parrot-linux-logo.jpg',
    categories: ['Todas as distros', 'Hacking', 'Raspberry', 'KDE', 'Plasma', 'Mate', 'XFCE'],
    basedOn: 'Debian',
    country: 'Itália',
    architecture: 'x64, arm',
    isoSize: '4 GB',
    officialSite: 'https://parrotsec.org/',
    description: 'Parrot OS é uma alternativa ao Kali Linux, com foco em segurança e desenvolvimento.',
    desktopEnvironments: 'MATE, KDE Plasma.',
    mainFeatures: 'Ferramentas de hacking, Sandbox.',
    packageManager: 'APT',
    preInstalledSoftware: 'Vasto arsenal de segurança.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Muito ativa.',
    comparison: 'Mais leve e versátil que o Kali para alguns.'
  },
  {
    id: 'solus',
    name: 'Solus OS',
    subtitle: 'Um sistema moderno para computadores modernos.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/images.png',
    categories: ['Todas as distros', 'Gnome', 'KDE', 'Plasma'],
    basedOn: 'Independente',
    country: 'Irlanda',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://getsol.us/',
    description: 'Solus é uma distro independente que foca em uso doméstico e multimídia.',
    desktopEnvironments: 'Budgie, GNOME, KDE Plasma.',
    mainFeatures: 'Ambiente Budgie, rolling release estável.',
    packageManager: 'eopkg',
    preInstalledSoftware: 'Firefox, LibreOffice, Rhythmbox.',
    hardwareCompatibility: 'Excelente para hardware moderno.',
    communitySupport: 'Crescente.',
    comparison: 'Experiência única com o desktop Budgie.'
  },
  {
    id: 'edubuntu',
    name: 'Edubuntu',
    subtitle: 'Linux para educação.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/images-1.png',
    categories: ['Todas as distros', 'Educação', 'Gnome'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64',
    isoSize: '5 GB',
    officialSite: 'https://www.edubuntu.org/',
    description: 'Edubuntu é a versão do Ubuntu focada em escolas e instituições de ensino.',
    desktopEnvironments: 'GNOME.',
    mainFeatures: 'Vasto conjunto de softwares educacionais.',
    packageManager: 'APT',
    preInstalledSoftware: 'GCompris, Tux4Kids, etc.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Comunidade educacional.',
    comparison: 'O melhor para laboratórios de informática.'
  },
  {
    id: 'kubuntu',
    name: 'Kubuntu',
    subtitle: 'Ubuntu com o poder do KDE Plasma.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Kubuntu_logo.svg_.png',
    categories: ['Todas as distros', 'KDE', 'Plasma'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64',
    isoSize: '3.5 GB',
    officialSite: 'https://kubuntu.org/',
    description: 'Kubuntu combina a base Ubuntu com o desktop KDE Plasma, altamente personalizável.',
    desktopEnvironments: 'KDE Plasma.',
    mainFeatures: 'Personalização extrema, base sólida.',
    packageManager: 'APT',
    preInstalledSoftware: 'KDE Apps, Firefox, LibreOffice.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Comunidade Ubuntu/KDE.',
    comparison: 'A melhor experiência KDE baseada em Ubuntu.'
  },
  {
    id: 'ubuntu-studio',
    name: 'Ubuntu Studio',
    subtitle: 'Uma estação de trabalho para criadores multimídia.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Ubuntustudio_v3_logo_only.svg_.png',
    categories: ['Todas as distros', 'Design', 'Multimidia', 'Gnome', 'KDE', 'Plasma', 'XFCE'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64',
    isoSize: '5 GB',
    officialSite: 'https://ubuntustudio.org/',
    description: 'Ubuntu Studio vem pré-configurado para edição de áudio, vídeo e imagem.',
    desktopEnvironments: 'KDE Plasma.',
    mainFeatures: 'Kernel low-latency, ferramentas de criação.',
    packageManager: 'APT',
    preInstalledSoftware: 'Ardour, Blender, Kdenlive, GIMP.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Comunidade de artistas.',
    comparison: 'A escolha definitiva para produção de conteúdo.'
  },
  {
    id: 'ubuntu-cinnamon',
    name: 'Ubuntu Cinnamon',
    subtitle: 'Ubuntu com o desktop Cinnamon.',
    logo: 'https://ubuntucinnamon.org/favicon.ico', // Ubuntu Cinnamon logo
    categories: ['Todas as distros', 'Cinnamon'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64',
    isoSize: '3 GB',
    officialSite: 'https://ubuntucinnamon.org/',
    description: 'Ubuntu Cinnamon oferece a experiência do desktop Cinnamon sobre a base Ubuntu.',
    desktopEnvironments: 'Cinnamon.',
    mainFeatures: 'Interface clássica, base Ubuntu.',
    packageManager: 'APT',
    preInstalledSoftware: 'Cinnamon Apps, Firefox.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Crescente.',
    comparison: 'Alternativa ao Linux Mint Cinnamon.'
  },
  {
    id: 'ubuntu-kylin',
    name: 'Ubuntu Kylin',
    subtitle: 'A edição chinesa do Ubuntu.',
    logo: 'https://www.ubuntukylin.com/favicon.ico', // Ubuntu Kylin logo
    categories: ['Todas as distros', 'KDE', 'Plasma'],
    basedOn: 'Ubuntu',
    country: 'China',
    architecture: 'x64, arm',
    isoSize: '4 GB',
    officialSite: 'https://www.ubuntukylin.com/',
    description: 'Ubuntu Kylin é adaptado para o mercado chinês com o desktop UKUI.',
    desktopEnvironments: 'UKUI.',
    mainFeatures: 'Localização chinesa, design moderno.',
    packageManager: 'APT',
    preInstalledSoftware: 'Apps locais chineses.',
    hardwareCompatibility: 'Boa.',
    communitySupport: 'Forte na China.',
    comparison: 'Focado em usuários de língua chinesa.'
  },
  {
    id: 'ubuntu-mate',
    name: 'Ubuntu MATE',
    subtitle: 'Retrospectiva clássica com tecnologias modernas.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Circle_of_MATEs.png',
    categories: ['Todas as distros', 'Raspberry', 'Mate'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64, arm',
    isoSize: '3 GB',
    officialSite: 'https://ubuntu-mate.org/',
    description: 'Ubuntu MATE usa o desktop MATE, continuação do clássico GNOME 2.',
    desktopEnvironments: 'MATE.',
    mainFeatures: 'MATE Tweak, Software Boutique.',
    packageManager: 'APT',
    preInstalledSoftware: 'MATE Apps, Firefox.',
    hardwareCompatibility: 'Excelente.',
    communitySupport: 'Muito ativa.',
    comparison: 'Para quem sente falta do GNOME antigo.'
  },
  {
    id: 'ubuntu-unity',
    name: 'Ubuntu Unity',
    subtitle: 'O retorno da interface Unity.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/ff79c36de908242bd0ceb05b8bb7fd3a2e51242e.png',
    categories: ['Todas as distros', 'Unity'],
    basedOn: 'Ubuntu',
    country: 'Global',
    architecture: 'x64',
    isoSize: '3 GB',
    officialSite: 'https://ubuntuunity.org/',
    description: 'Ubuntu Unity traz de volta o ambiente Unity que foi padrão no Ubuntu por anos.',
    desktopEnvironments: 'Unity.',
    mainFeatures: 'Interface Unity 7, base Ubuntu.',
    packageManager: 'APT',
    preInstalledSoftware: 'Unity Apps, Firefox.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Comunidade nostálgica.',
    comparison: 'Para fãs do workflow do Unity original.'
  },
  {
    id: 'regata-os',
    name: 'Regata OS',
    subtitle: 'Focado em jogos e produtividade, feito no Brasil.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/regata.webp',
    categories: ['Todas as distros', 'Brasileira', 'Jogos', 'KDE', 'Plasma', 'XFCE'],
    basedOn: 'openSUSE',
    country: 'Brasil',
    architecture: 'x64',
    isoSize: '3.5 GB',
    officialSite: 'https://www.regataos.com.br/',
    description: 'Regata OS é uma distro brasileira otimizada para gamers e criadores.',
    desktopEnvironments: 'KDE Plasma.',
    mainFeatures: 'Regata OS Game Mode, suporte a drivers.',
    packageManager: 'Zypper',
    preInstalledSoftware: 'Steam, Heroic Games Launcher.',
    hardwareCompatibility: 'Excelente para jogos.',
    communitySupport: 'Comunidade brasileira.',
    comparison: 'Uma das melhores opções para gamers no Brasil.'
  },
  {
    id: 'tiger-os',
    name: 'Tiger OS',
    subtitle: 'Foco em produtividade e empresas.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/logo-tiger-os-logotipo-min-3-e1669940988169.webp',
    categories: ['Todas as distros', 'Brasileira', 'KDE', 'Plasma', 'XFCE'],
    basedOn: 'Ubuntu',
    country: 'Brasil',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://tigeros.com.br/',
    description: 'Tiger OS é uma distro brasileira focada no mercado corporativo e produtividade.',
    desktopEnvironments: 'XFCE.',
    mainFeatures: 'Estabilidade, ferramentas de produtividade.',
    packageManager: 'APT',
    preInstalledSoftware: 'LibreOffice, Firefox.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Brasileira.',
    comparison: 'Ideal para escritórios.'
  },
  {
    id: 'mauna',
    name: 'Mauna Linux',
    subtitle: 'Simplicidade e beleza.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/images.jpeg',
    categories: ['Todas as distros', 'Brasileira', 'Cinnamon', 'LXQt', 'Mate'],
    basedOn: 'Debian',
    country: 'Brasil',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://maunalinux.org/',
    description: 'Mauna Linux é um projeto brasileiro que busca oferecer um sistema polido e fácil.',
    desktopEnvironments: 'Cinnamon, MATE, LXQt.',
    mainFeatures: 'Fácil instalação, visual limpo.',
    packageManager: 'APT',
    preInstalledSoftware: 'Firefox, LibreOffice.',
    hardwareCompatibility: 'Boa.',
    communitySupport: 'Brasileira.',
    comparison: 'Focado no usuário final.'
  },
  {
    id: 'steam-os',
    name: 'Steam OS',
    subtitle: 'O sistema do Steam Deck, focado em jogos.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/my6iq6r1imx586svppvfnuw20skkdpn8-e1772048809779.png',
    categories: ['Todas as distros', 'Jogos'],
    basedOn: 'Arch',
    country: 'EUA',
    architecture: 'x64',
    isoSize: 'Varia',
    officialSite: 'https://store.steampowered.com/steamos',
    description: 'SteamOS é projetado para oferecer a melhor experiência de jogo possível.',
    desktopEnvironments: 'KDE Plasma (modo desktop).',
    mainFeatures: 'Interface Steam, Gamescope, Proton.',
    packageManager: 'Pacman (read-only por padrão)',
    preInstalledSoftware: 'Steam.',
    hardwareCompatibility: 'Otimizado para o Steam Deck.',
    communitySupport: 'Enorme comunidade gamer.',
    comparison: 'O futuro do Linux nos jogos.'
  },
  {
    id: 'endless-os',
    name: 'Endless OS',
    subtitle: 'Conhecimento para todos, mesmo sem internet.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/images-2.png',
    categories: ['Todas as distros', 'Educação'],
    basedOn: 'Debian',
    country: 'EUA',
    architecture: 'x64, arm',
    isoSize: 'Varia (até 16GB)',
    officialSite: 'https://endlessos.com/',
    description: 'Endless OS vem com centenas de aplicativos pré-instalados para uso offline.',
    desktopEnvironments: 'Custom GNOME.',
    mainFeatures: 'Conteúdo offline, interface simples.',
    packageManager: 'Flatpak',
    preInstalledSoftware: 'Enciclopédia, Vídeos educativos, Office.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Focada em inclusão digital.',
    comparison: 'Único em sua proposta offline.'
  },
  {
    id: 'br-os',
    name: 'Br OS',
    subtitle: 'O sistema brasileiro para o dia a dia.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/images-1.jpeg',
    categories: ['Todas as distros', 'Brasileira', 'KDE', 'Plasma'],
    basedOn: 'Ubuntu',
    country: 'Brasil',
    architecture: 'x64',
    isoSize: '3 GB',
    officialSite: 'https://bros.org.br/',
    description: 'Br OS foca em ser um sistema completo e familiar para brasileiros.',
    desktopEnvironments: 'KDE Plasma.',
    mainFeatures: 'Visual polido, ferramentas brasileiras.',
    packageManager: 'APT',
    preInstalledSoftware: 'LibreOffice, Firefox.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Brasileira.',
    comparison: 'Fácil e direto ao ponto.'
  },
  {
    id: 'chrome-os-flex',
    name: 'Chrome OS Flex',
    subtitle: 'Transforme seu PC antigo em um Chromebook.',
    logo: 'https://www.google.com/chrome/static/images/chrome-logo.svg',
    categories: ['Todas as distros', 'Educação'],
    basedOn: 'Gentoo (ChromeOS)',
    country: 'EUA',
    architecture: 'x64',
    isoSize: 'Varia',
    officialSite: 'https://chromeenterprise.google/os/chromeosflex/',
    description: 'Chrome OS Flex é a versão do Google para PCs e Macs antigos.',
    desktopEnvironments: 'ChromeOS Shell.',
    mainFeatures: 'Rápido, seguro, focado na web.',
    packageManager: 'Nenhum (focado em Web Apps)',
    preInstalledSoftware: 'Chrome Browser.',
    hardwareCompatibility: 'Lista de modelos certificados.',
    communitySupport: 'Suporte Google.',
    comparison: 'O mais simples e limitado, mas muito rápido.'
  },
  {
    id: 'fyde-os',
    name: 'Fyde OS',
    subtitle: 'ChromeOS com suporte a apps Android.',
    logo: 'https://fydeos.io/favicon.ico', // Fyde OS logo
    categories: ['Todas as distros', 'Jogos'],
    basedOn: 'Chromium OS',
    country: 'China',
    architecture: 'x64, arm',
    isoSize: '2.5 GB',
    officialSite: 'https://fydeos.io/',
    description: 'FydeOS é um fork do Chromium OS que adiciona suporte a apps Android e Linux.',
    desktopEnvironments: 'Chromium Shell.',
    mainFeatures: 'Suporte Android, rápido.',
    packageManager: 'Android/Linux Container.',
    preInstalledSoftware: 'Chromium.',
    hardwareCompatibility: 'Boa.',
    communitySupport: 'Crescente.',
    comparison: 'Chromium OS com mais recursos.'
  },
  {
    id: 'red-hat',
    name: 'Red Hat Enterprise Linux',
    subtitle: 'O padrão corporativo para servidores e nuvem.',
    logo: 'https://www.redhat.com/favicon.ico', // Red Hat logo
    categories: ['Todas as distros', 'Servidor', 'Gnome', 'KDE', 'Plasma'],
    basedOn: 'Independente',
    country: 'EUA',
    architecture: 'x64, arm, s390x',
    isoSize: 'Varia',
    officialSite: 'https://www.redhat.com/',
    description: 'RHEL é a distribuição comercial líder para empresas.',
    desktopEnvironments: 'GNOME.',
    mainFeatures: 'Estabilidade extrema, suporte pago.',
    packageManager: 'DNF',
    preInstalledSoftware: 'Ferramentas de servidor.',
    hardwareCompatibility: 'Certificada para hardware corporativo.',
    communitySupport: 'Suporte profissional.',
    comparison: 'O rei dos servidores corporativos.'
  },
  {
    id: 'gentoo',
    name: 'Gentoo',
    subtitle: 'Personalização total através da compilação.',
    logo: 'https://www.gentoo.org/assets/img/logo/gentoo-logo.png',
    categories: ['Todas as distros', 'Servidor', 'Cinnamon', 'Gnome', 'KDE', 'Plasma', 'LXQt', 'Mate', 'XFCE'],
    basedOn: 'Independente',
    country: 'Global',
    architecture: 'Múltiplas',
    isoSize: 'Varia',
    officialSite: 'https://www.gentoo.org/',
    description: 'Gentoo é uma distro onde o usuário compila quase tudo para seu hardware específico.',
    desktopEnvironments: 'Qualquer um.',
    mainFeatures: 'Portage, compilação de código fonte.',
    packageManager: 'Portage',
    preInstalledSoftware: 'Mínimo.',
    hardwareCompatibility: 'Extrema (se você souber configurar).',
    communitySupport: 'Comunidade técnica avançada.',
    comparison: 'Para quem quer o máximo de performance e controle.'
  },
  {
    id: 'antix',
    name: 'AntiX',
    subtitle: 'Leveza extrema sem systemd.',
    logo: 'https://antixlinux.com/favicon.ico', // AntiX logo
    categories: ['Todas as distros', 'Pc antigo'],
    basedOn: 'Debian',
    country: 'Grécia',
    architecture: 'x64, x86',
    isoSize: '1.2 GB',
    officialSite: 'https://antixlinux.com/',
    description: 'AntiX é projetado para ser rápido e leve em computadores muito antigos.',
    desktopEnvironments: 'IceWM, Fluxbox.',
    mainFeatures: 'Sem systemd, muito leve.',
    packageManager: 'APT',
    preInstalledSoftware: 'Leves.',
    hardwareCompatibility: 'Incrível para hardware legado.',
    communitySupport: 'Dedicada.',
    comparison: 'Uma das melhores para reviver PCs de 15 anos atrás.'
  },
  {
    id: 'alpine',
    name: 'Alpine Linux',
    subtitle: 'Segurança, simplicidade e eficiência em containers.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/lcKcGurx_400x400.png',
    categories: ['Todas as distros', 'Raspberry', 'Servidor', 'LXQt', 'Mate', 'XFCE'],
    basedOn: 'Independente',
    country: 'Global',
    architecture: 'Múltiplas',
    isoSize: '150 MB',
    officialSite: 'https://alpinelinux.org/',
    description: 'Alpine é uma distro focada em segurança e tamanho reduzido, muito usada em Docker.',
    desktopEnvironments: 'Mínimo (pode instalar outros).',
    mainFeatures: 'musl libc, BusyBox, muito pequeno.',
    packageManager: 'apk',
    preInstalledSoftware: 'Mínimo.',
    hardwareCompatibility: 'Boa para servidores.',
    communitySupport: 'Focada em DevOps.',
    comparison: 'A base preferida para containers Docker.'
  },
  {
    id: 'void',
    name: 'Void Linux',
    subtitle: 'Uma distro independente e estável.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/Void_Linux_logo.svg_.png',
    categories: ['Todas as distros', 'Servidor', 'LXQt', 'Mate', 'XFCE'],
    basedOn: 'Independente',
    country: 'Global',
    architecture: 'x64, arm',
    isoSize: '800 MB',
    officialSite: 'https://voidlinux.org/',
    description: 'Void Linux usa o sistema de init runit e foca em estabilidade e simplicidade.',
    desktopEnvironments: 'XFCE, KDE, Gnome, etc.',
    mainFeatures: 'XBPS, runit, rolling release.',
    packageManager: 'XBPS',
    preInstalledSoftware: 'Mínimo.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Técnica.',
    comparison: 'Alternativa única ao Arch e Debian.'
  },
  {
    id: 'raspberry-pi-os',
    name: 'Raspberry Pi OS',
    subtitle: 'O sistema oficial para o Raspberry Pi.',
    logo: 'https://www.raspberrypi.com/favicon.ico', // Raspberry Pi OS logo
    categories: ['Todas as distros', 'Raspberry'],
    basedOn: 'Debian',
    country: 'Reino Unido',
    architecture: 'arm',
    isoSize: '1 GB',
    officialSite: 'https://www.raspberrypi.com/software/',
    description: 'Raspberry Pi OS é otimizado para o hardware do Raspberry Pi.',
    desktopEnvironments: 'PIXEL (baseado em LXDE).',
    mainFeatures: 'Otimizado para ARM, ferramentas educacionais.',
    packageManager: 'APT',
    preInstalledSoftware: 'Python, Scratch, Mathematica.',
    hardwareCompatibility: 'Perfeita para Raspberry Pi.',
    communitySupport: 'Gigante.',
    comparison: 'O padrão para computação em placa única.'
  },
  {
    id: 'black-arch',
    name: 'Black Arch',
    subtitle: 'Hacking e segurança baseada em Arch.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/BlackArch_logo.png',
    categories: ['Todas as distros', 'Hacking', 'Raspberry', 'KDE', 'Plasma', 'Mate', 'XFCE'],
    basedOn: 'Arch',
    country: 'Global',
    architecture: 'x64, arm',
    isoSize: '18 GB (Full)',
    officialSite: 'https://blackarch.org/',
    description: 'BlackArch contém milhares de ferramentas para testes de segurança.',
    desktopEnvironments: 'Vários gerenciadores de janela.',
    mainFeatures: 'Mais de 2800 ferramentas de segurança.',
    packageManager: 'Pacman',
    preInstalledSoftware: 'Arsenal completo de hacking.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Técnica.',
    comparison: 'O maior repositório de ferramentas de segurança.'
  },
  {
    id: 'backbox',
    name: 'BackBox',
    subtitle: 'Testes de penetração e avaliação de segurança.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/png-clipart-backbox-linux-distribution-linux-mint-operating-systems-linux-blue-text.png',
    categories: ['Todas as distros', 'Hacking', 'LXDE', 'XFCE'],
    basedOn: 'Ubuntu',
    country: 'Itália',
    architecture: 'x64',
    isoSize: '2.5 GB',
    officialSite: 'https://www.backbox.org/',
    description: 'BackBox é uma distro baseada em Ubuntu focada em análise forense e segurança.',
    desktopEnvironments: 'XFCE.',
    mainFeatures: 'Ferramentas de segurança, leveza.',
    packageManager: 'APT',
    preInstalledSoftware: 'Ferramentas de segurança.',
    hardwareCompatibility: 'Alta.',
    communitySupport: 'Ativa.',
    comparison: 'Alternativa estável ao Kali baseada em Ubuntu.'
  },
  {
    id: 'tuxedo-os',
    name: 'Tuxedo OS',
    subtitle: 'Otimizado para hardware TUXEDO e muito mais.',
    logo: 'https://meulinux.com.br/wp-content/uploads/2026/02/23074477.png',
    categories: ['Todas as distros', 'KDE', 'Plasma', 'XFCE'],
    basedOn: 'Ubuntu',
    country: 'Alemanha',
    architecture: 'x64',
    isoSize: '3 GB',
    officialSite: 'https://www.tuxedocomputers.com/en/TUXEDO-OS.tuxedo',
    description: 'Tuxedo OS é uma distro polida baseada em Ubuntu com KDE Plasma.',
    desktopEnvironments: 'KDE Plasma.',
    mainFeatures: 'Drivers otimizados, visual moderno.',
    packageManager: 'APT',
    preInstalledSoftware: 'KDE Apps, Firefox.',
    hardwareCompatibility: 'Excelente, especialmente em laptops.',
    communitySupport: 'Crescente.',
    comparison: 'Uma das melhores implementações de KDE Plasma.'
  }
];

export const CATEGORIES = [
  "Todas as distros", "Pc antigo", "Brasileira", "Hacking", "Jogos", "Educação", 
  "Raspberry", "Design", "Servidor", "Cinnamon", "Gnome", "KDE", "LXDE", "LXQt", 
  "Mate", "Pantheon", "Plasma", "Unity", "XFCE", "Multimidia"
];

export const DISTRO_LIST_NAMES = DISTROS.map(d => d.name);

